import "./globals.css";
import styles from "./layout.module.css";
import Footer from "@/components/Footer";
import { League_Spartan } from "@next/font/google";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const leagueSpartan = League_Spartan({
  subsets: ["latin"],
  weight: ["500", "700"],
});

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${styles.layout} ${leagueSpartan.className}`}>
        {children} <Footer />
      </body>
    </html>
  );
}
